# Generated by Django 4.2.7 on 2023-12-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseName", models.CharField(max_length=100)),
                ("courseDescription", models.TextField()),
                ("courseImagePath", models.CharField(max_length=250)),
                ("coursePrice", models.FloatField()),
                ("instructorName", models.CharField(max_length=100)),
                ("courseCategory", models.CharField(max_length=50)),
                ("courseReleaseDate", models.DateTimeField()),
                ("isEnrollable", models.BooleanField()),
                ("isAvailable", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discussionTitle", models.CharField(max_length=100)),
                ("discussionContent", models.TextField()),
                ("authorName", models.CharField(max_length=100)),
                ("postDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollmentDate", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todosAPI.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("profileImage", models.CharField(max_length=250)),
                (
                    "enrolledCourses",
                    models.ManyToManyField(
                        through="todosAPI.Enrollment", to="todosAPI.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lessonTitle", models.CharField(max_length=100)),
                ("lessonDescription", models.TextField()),
                ("videoUrl", models.CharField(max_length=250)),
                ("lessonReleaseDate", models.DateTimeField()),
                ("isAvailable", models.BooleanField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todosAPI.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todosAPI.user"
            ),
        ),
    ]
