# Generated by Django 4.2.7 on 2023-12-29 21:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("todosAPI", "0002_alter_user_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profileImage",
            field=models.URLField(
                blank=True,
                default="https://static.vecteezy.com/system/resources/previews/020/765/399/non_2x/default-profile-account-unknown-icon-black-silhouette-free-vector.jpg",
                max_length=250,
                null=True,
            ),
        ),
    ]
