# Generated by Django 4.2.7 on 2023-12-29 22:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("todosAPI", "0003_user_phonenumber_alter_user_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="01101990633", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
